; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
MessagesFile=compiler:Dutch.isl
AppName=Syscalculator Euro Edition
AppVerName=Syscalculator Euro Edition 1.62 Nederlands
AppPublisher=Tiedragon
AppPublisherURL=https://www.tiedragon.com
AppSupportURL=https://www.tiedragon.com
AppUpdatesURL=https://www.tiedragon.com
DefaultDirName={pf}\Syscalculator Euro Edition
DefaultGroupName=Tiedragon
LicenseFile=license.rtf
InfoBeforeFile=readme.rtf
WizardImageFile=Picture 9.bmp
WizardSmallImageFile=icon4.bmp
; uncomment the following line if you want your installation to run on NT 3.51 too.
; MinVersion=4,3.51

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:"; MinVersion: 4,4
Name: "quicklaunchicon"; Description: "Create a &Quick Launch icon"; GroupDescription: "Additional icons:"; MinVersion: 4,4; Flags: unchecked

[Files]
Source: "help\index_en.htm"; DestDir: "{app}\help\"; CopyMode: alwaysoverwrite
Source: "help\index_nl.htm"; DestDir: "{app}\help\"; CopyMode: alwaysoverwrite
Source: "help\Syscal_1.png"; DestDir: "{app}\help\"; CopyMode: alwaysoverwrite
Source: "help\Syscal_2.png"; DestDir: "{app}\help\"; CopyMode: alwaysoverwrite
Source: "help\Syscal_3.png"; DestDir: "{app}\help\"; CopyMode: alwaysoverwrite
Source: "help\Syscal_4.png"; DestDir: "{app}\help\"; CopyMode: alwaysoverwrite
Source: "help\triconvert_3.jpg"; DestDir: "{app}\help\"; CopyMode: alwaysoverwrite
Source: "help\decimals.jpg"; DestDir: "{app}\help\"; CopyMode: alwaysoverwrite
Source: "freesyscal.exe"; DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: "euro\FRF.nod"; DestDir: "{app}\euro\"; CopyMode: alwaysoverwrite
Source: "euro\IEP.nod"; DestDir: "{app}\euro\"; CopyMode: alwaysoverwrite
Source: "euro\itl.nod"; DestDir: "{app}\euro\"; CopyMode: alwaysoverwrite
Source: "euro\GRD.nod"; DestDir: "{app}\euro\"; CopyMode: alwaysoverwrite
Source: "euro\NLG.nod"; DestDir: "{app}\euro\"; CopyMode: alwaysoverwrite
Source: "euro\PTE.nod"; DestDir: "{app}\euro\"; CopyMode: alwaysoverwrite
Source: "readme.txt"; DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: "euro\ESP.nod"; DestDir: "{app}\euro\"; CopyMode: alwaysoverwrite
Source: "euro\FIM.nod"; DestDir: "{app}\euro"; CopyMode: alwaysoverwrite
Source: "freesyscal.cfg"; DestDir: "{app}"; CopyMode: alwaysskipifsameorolder
Source: "euro\DEM.nod"; DestDir: "{app}\euro\"; CopyMode: alwaysoverwrite
Source: "euro\ats.nod"; DestDir: "{app}\euro\"; CopyMode: alwaysoverwrite
Source: "euro\BEF.nod"; DestDir: "{app}\euro\"; CopyMode: alwaysoverwrite
Source: "euro\LUF.nod"; DestDir: "{app}\euro\"; CopyMode: alwaysoverwrite
Source: "config.nod"; DestDir: "{app}\euro\"; CopyMode: alwaysoverwrite
Source: "eng.lng"; DestDir: "{app}\euro\"; CopyMode: alwaysoverwrite
Source: "esp.lng"; DestDir: "{app}\euro\"; CopyMode: alwaysoverwrite
Source: "ned.lng"; DestDir: "{app}\euro\"; CopyMode: alwaysoverwrite

[Icons]
Name: "{group}\Syscalculator Euro Edition"; Filename: "{app}\freesyscal.exe"
Name: "{userdesktop}\Syscalculator Euro Edition"; Filename: "{app}\freesyscal.exe"; MinVersion: 4,4; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\Syscalculator Euro Edition"; Filename: "{app}\freesyscal.exe"; MinVersion: 4,4; Tasks: quicklaunchicon
[Registry]
Root: HKLM; Subkey: "Software\Tiedragon\Syscalculator Euro Edition"; Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\Tiedragon\"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run";  ValueName: "Syscal"; Flags: uninsdeletevalue

[Run]
Filename: "{app}\freesyscal.exe" ; Parameters: "/Once"; Description: "Launch Syscalculator Euro Edition"; Flags: nowait postinstall skipifsilent

