; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Tab Manager 2003 Compiler for MSN
AppVerName=Tab Manager 2003 Compiler for MSN
AppPublisher=Tcsoftware
AppPublisherURL=http://www.tcsoftware.com
AppSupportURL=http://www.tcsoftware.com
AppUpdatesURL=http://www.tcsoftware.com
DefaultDirName={pf}\Tab Manager 2003 for MSN
DefaultGroupName=Tab Manager 2003 for MSN
LicenseFile=C:\www.tweakers\license.txt

[Tasks]
; NOTE: The following entry contains English phrases ("Create a desktop icon" and "Additional icons"). You are free to translate them into another language if required.
Name: desktopicon; Description: Create a &desktop icon; GroupDescription: Additional icons:

[Files]
Source: C:\compilertab\Tabcompiler.exe; DestDir: {app}; Flags: ignoreversion
Source: C:\compilertab\MSNpatch.bin; DestDir: {app}; Flags: ignoreversion
Source: ..\compilertab\tabcompiler.cfg; DestDir: {app}; Flags: ignoreversion
Source: engels.lrg; DestDir: {app}
Source: ..\compilertab\nederlands.lrg; DestDir: {app}
Source: ..\compilertab\English.lng; DestDir: {app}
Source: ..\compilertab\Spanish.lrg; DestDir: {app}
Source: ..\compilertab\spanisch.lng; DestDir: {app}
Source: ..\compilertab\francais.lng; DestDir: {app}
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Tab Manager 2003 for MSN "; Filename: {app}\tabcompiler.exe; IconIndex: 0
Name: "{userdesktop}\Tab Manager 2003 for MSN "; Filename: {app}\tabcompiler.exe; Tasks: desktopicon

[Run]
; NOTE: The following entry contains an English phrase ("Launch"). You are free to translate it into another language if required.
Filename: {app}\tabcompiler.exe; Description: "Launch Tab Manager 2003 for MSN "; Flags: nowait postinstall skipifsilent; Parameters: /lng {app}\engels.lrg; Languages: eng; WorkingDir: {app}
Filename: {app}\Tabcompiler.exe; Parameters: /lng {app}\nederlands.lrg; Languages: dutch; Flags: nowait postinstall skipifsilent; WorkingDir: {app}
Filename: {app}\Tabcompiler.exe; Parameters: /lng {app}\spanish.lrg; WorkingDir: {app}; Languages: es; Flags: nowait postinstall skipifsilent

[_ISTool]
EnableISX=false

[Registry]
Root: HKCU; Subkey: SOFTWARE\Tiedragon\
Root: HKCU; Subkey: SOFTWARE\Tiedragon\Tabmanager\
Root: HKCU; Subkey: SOFTWARE\Tiedragon\Tabmanager\; ValueType: string; ValueName: Language
Root: HKCR; SubKey: ft000003; ValueType: string; ValueData: ; Flags: uninsdeletekey
Root: HKCR; SubKey: ft000003; ValueType: dword; ValueName: EditFlags; ValueData: 00000000; Flags: uninsdeletekey
Root: HKCR; SubKey: ft000003; ValueType: dword; ValueName: BrowserFlags; ValueData: 00000008; Flags: uninsdeletekey
Root: HKCR; SubKey: ft000003\DefaultIcon; ValueType: string; ValueData: {app}\Tabcompiler.exe,0; Flags: uninsdeletekey
Root: HKCR; SubKey: ft000003\Shell; ValueType: string; ValueData: open; Flags: uninsdeletekey
Root: HKCR; SubKey: ft000003\Shell\open; Flags: uninsdeletekey
Root: HKCR; SubKey: ft000003\Shell\open\command; ValueType: string; ValueData: """{app}\Tabcompiler.exe""/file %1"; Flags: uninsdeletekey
Root: HKCR; SubKey: ft000003\Shell\open\ddeexec; Flags: uninsdeletekey
Root: HKCR; SubKey: ft000003\Shell\open\ddeexec\Application; ValueType: string; ValueData: Tabcompiler; Flags: uninsdeletekey
Root: HKCR; SubKey: ft000003\Shell\open\ddeexec\Topic; ValueType: string; ValueData: System; Flags: uninsdeletekey
Root: HKCR; SubKey: ft000003\Shell\edit; Flags: uninsdeletekey
Root: HKCR; SubKey: ft000003\Shell\edit\command; ValueType: string; ValueData: """{app}\Tabcompiler.exe""/file  %1"; Flags: uninsdeletekey
Root: HKCR; SubKey: .prj; ValueType: string; ValueData: ft000003; Flags: uninsdeletekey
Root: HKCU; Subkey: Software\Tiedragon\Tabmanager; ValueType: string; ValueName: Migration; ValueData: 1; Flags: createvalueifdoesntexist

[Languages]
Name: eng; MessagesFile: C:\Program Files\Inno Setup 4\Default.isl; LicenseFile: C:\www.tweakers\license.txt
Name: NL; MessagesFile: C:\Program Files\Inno Setup 4\Dutch.isl; LicenseFile: C:\compilertab\licentienl.txt
Name: es; MessagesFile: C:\Program Files\Inno Setup 4\SpanishStd.isl; LicenseFile: C:\www.tweakers\license.txt
