<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Syscalculator.Updater</AssemblyName>
    <Title>Syscalculator Updater</Title>
    <Product>Syscalculator</Product>
    <Company>Tiedragon</Company>
    <Version>2.0.0</Version>
    <FileVersion>2.0.0.0</FileVersion>
    <InformationalVersion>2.0.0</InformationalVersion>
    <ApplicationIcon>..\syscalculator\Resources\Syscalculator.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
