<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Tiedragon.Graph.2D</AssemblyName>
    <Title>Tiedragon.Graph.2D</Title>
    <Product>Tiedragon.Graph.2D</Product>
    <Company>Tiedragon</Company>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tiedragon.Graph\Tiedragon.Graph.csproj" />
  </ItemGroup>

</Project>
