<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Tiedragon.Graph</AssemblyName>
    <Title>Tiedragon.Graph</Title>
    <Product>Tiedragon.Graph</Product>
    <Company>Tiedragon</Company>
    <Version>0.1.0</Version>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

</Project>
